### PR TITLE
Flutter skeletal file with hello world

### PR DESCRIPTION
**Pull request by mysticetii**
it is for https://github.com/Geovation/flutter_sandbox/issues/1. The associated file was created from template file and updated to have a text widget with hello world text in the centre

### CODE REVIEW

**Review by sebastianovide — CHANGES_REQUESTED** [review]
cannot see any documentation explaining how to run it

**Comment by mysticetii** [comment]
This link describes how to run the flutter app in three modes android studio, vs code, terminal. Should I add this link to the readme file?

https://flutter.dev/docs/get-started/test-drive

**Comment by joykuotw** [comment]
Sure, add description with the link to guide the users how to run the app.

**Review by sebastianovide — APPROVED** [review]

**Comment by joykuotw** [comment]
merge it for now but we will tweak the instructions later.

**Pull request merged**
